// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsz7TEqPDtZdxFk3eTSvo11Q8YRQDVU4w',
    appId: '1:130497814341:web:83569103a69c0b9fc8282c',
    messagingSenderId: '130497814341',
    projectId: 'menu-mentor-prod',
    authDomain: 'menu-mentor-prod.firebaseapp.com',
    storageBucket: 'menu-mentor-prod.firebasestorage.app',
    measurementId: 'G-2WQKQX1RW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DSCyL4gHAAVkrrTy-Ty1_K3VecTiq0E',
    appId: '1:130497814341:android:776076ecb482da47c8282c',
    messagingSenderId: '130497814341',
    projectId: 'menu-mentor-prod',
    storageBucket: 'menu-mentor-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2l_-SBwPcxPVO4tiPc5Du6C1wcDk81o',
    appId: '1:130497814341:ios:da70362be61c6473c8282c',
    messagingSenderId: '130497814341',
    projectId: 'menu-mentor-prod',
    storageBucket: 'menu-mentor-prod.firebasestorage.app',
    iosClientId: '130497814341-s06m1ikgim60ctmffpi6j44ldsl7look.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuMentorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2l_-SBwPcxPVO4tiPc5Du6C1wcDk81o',
    appId: '1:130497814341:ios:da70362be61c6473c8282c',
    messagingSenderId: '130497814341',
    projectId: 'menu-mentor-prod',
    storageBucket: 'menu-mentor-prod.firebasestorage.app',
    iosClientId: '130497814341-s06m1ikgim60ctmffpi6j44ldsl7look.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuMentorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsz7TEqPDtZdxFk3eTSvo11Q8YRQDVU4w',
    appId: '1:130497814341:web:e9c20892de84df7bc8282c',
    messagingSenderId: '130497814341',
    projectId: 'menu-mentor-prod',
    authDomain: 'menu-mentor-prod.firebaseapp.com',
    storageBucket: 'menu-mentor-prod.firebasestorage.app',
    measurementId: 'G-JCPDYWZTB6',
  );
}
